export interface Commodity {
  id: string;
  name: string;
  category: COMMODITY_CATEGORIES;
  unit: string; // e.g., "kg", "piece", "liter"
  type?: string; // Product type (e.g., "Premium", "Well Milled", "Special")
  specification?: string; // Product specification (e.g., "5% broken", "Medium size")
  currentPrice?: number;
  priceDate?: string;
  priceSource?: string;
  priceSpecification?: string;
  priceChange?: number; // percentage change
  priceChangePercent?: number; // percentage change (alternative name)
  priceChangeDirection?: 'up' | 'down' | 'stable';
  lastUpdated?: string;
  forecast?: {
    nextWeek: number;
    nextMonth: number;
    confidence: number; // 0-100
    factors: string[]; // e.g., "seasonal demand", "supply shortage"
    trend?: 'up' | 'down' | 'stable';
  };
}

export enum COMMODITY_CATEGORIES {
  BEEF_MEAT_PRODUCTS = 'BEEF MEAT PRODUCTS',
  CORN_PRODUCTS = 'CORN PRODUCTS',
  FISH_PRODUCTS = 'FISH PRODUCTS',
  FRUITS = 'FRUITS',
  HIGHLAND_VEGETABLES = 'HIGHLAND VEGETABLES',
  IMPORTED_COMMERCIAL_RICE = 'IMPORTED COMMERCIAL RICE',
  KADIWA_RICE_FOR_ALL = 'KADIWA RICE-FOR-ALL',
  LIVESTOCK_AND_POULTRY_PRODUCTS = 'LIVESTOCK AND POULTRY PRODUCTS',
  LOCAL_COMMERCIAL_RICE = 'LOCAL COMMERCIAL RICE',
  LOWLAND_VEGETABLES = 'LOWLAND VEGETABLES',
  OTHER_BASIC_COMMODITIES = 'OTHER BASIC COMMODITIES',
  OTHER_LIVESTOCK_MEAT_PRODUCTS = 'OTHER LIVESTOCK MEAT PRODUCTS',
  PORK_MEAT_PRODUCTS = 'PORK MEAT PRODUCTS',
  POULTRY_PRODUCTS = 'POULTRY PRODUCTS',
  SPICES = 'SPICES',
}

export const COMMODITY_DATA: Commodity[] = [
  {
    id: 'beef-meat-products-beef-brisket-imported',
    name: 'Beef Brisket, Imported',
    category: COMMODITY_CATEGORIES.BEEF_MEAT_PRODUCTS,
    unit: 'kg',
    type: 'Beef Brisket, Imported',
  },
  {
    id: 'beef-meat-products-beef-brisket-local-meat-with-bones',
    name: 'Beef Brisket, Local',
    category: COMMODITY_CATEGORIES.BEEF_MEAT_PRODUCTS,
    unit: 'kg',
    type: 'Beef Brisket, Local',
    specification: 'Meat with Bones',
  },
  {
    id: 'beef-meat-products-beef-chuck-imported',
    name: 'Beef Chuck, Imported',
    category: COMMODITY_CATEGORIES.BEEF_MEAT_PRODUCTS,
    unit: 'kg',
    type: 'Beef Chuck, Imported',
  },
  {
    id: 'beef-meat-products-beef-chuck-local',
    name: 'Beef Chuck, Local',
    category: COMMODITY_CATEGORIES.BEEF_MEAT_PRODUCTS,
    unit: 'kg',
    type: 'Beef Chuck, Local',
  },
  {
    id: 'beef-meat-products-beef-flank-imported',
    name: 'Beef Flank, Imported',
    category: COMMODITY_CATEGORIES.BEEF_MEAT_PRODUCTS,
    unit: 'kg',
    type: 'Beef Flank, Imported',
  },
  {
    id: 'beef-meat-products-beef-flank-local',
    name: 'Beef Flank, Local',
    category: COMMODITY_CATEGORIES.BEEF_MEAT_PRODUCTS,
    unit: 'kg',
    type: 'Beef Flank, Local',
  },
  {
    id: 'beef-meat-products-beef-fore-limb-imported',
    name: 'Beef Fore Limb, Imported',
    category: COMMODITY_CATEGORIES.BEEF_MEAT_PRODUCTS,
    unit: 'kg',
    type: 'Beef Fore Limb, Imported',
  },
  {
    id: 'beef-meat-products-beef-fore-limb-local',
    name: 'Beef Fore Limb, Local',
    category: COMMODITY_CATEGORIES.BEEF_MEAT_PRODUCTS,
    unit: 'kg',
    type: 'Beef Fore Limb, Local',
  },
  {
    id: 'beef-meat-products-beef-forequarter-imported',
    name: 'Beef Forequarter, Imported',
    category: COMMODITY_CATEGORIES.BEEF_MEAT_PRODUCTS,
    unit: 'kg',
    type: 'Beef Forequarter, Imported',
  },
  {
    id: 'beef-meat-products-beef-forequarter-local',
    name: 'Beef Forequarter, Local',
    category: COMMODITY_CATEGORIES.BEEF_MEAT_PRODUCTS,
    unit: 'kg',
    type: 'Beef Forequarter, Local',
  },
  {
    id: 'beef-meat-products-beef-loin-imported',
    name: 'Beef Loin, Imported',
    category: COMMODITY_CATEGORIES.BEEF_MEAT_PRODUCTS,
    unit: 'kg',
    type: 'Beef Loin, Imported',
  },
  {
    id: 'beef-meat-products-beef-loin-local',
    name: 'Beef Loin, Local',
    category: COMMODITY_CATEGORIES.BEEF_MEAT_PRODUCTS,
    unit: 'kg',
    type: 'Beef Loin, Local',
  },
  {
    id: 'beef-meat-products-beef-plate-imported',
    name: 'Beef Plate, Imported',
    category: COMMODITY_CATEGORIES.BEEF_MEAT_PRODUCTS,
    unit: 'kg',
    type: 'Beef Plate, Imported',
  },
  {
    id: 'beef-meat-products-beef-plate-local',
    name: 'Beef Plate, Local',
    category: COMMODITY_CATEGORIES.BEEF_MEAT_PRODUCTS,
    unit: 'kg',
    type: 'Beef Plate, Local',
  },
  {
    id: 'beef-meat-products-beef-rib-eye-imported',
    name: 'Beef Rib Eye, Imported',
    category: COMMODITY_CATEGORIES.BEEF_MEAT_PRODUCTS,
    unit: 'kg',
    type: 'Beef Rib Eye, Imported',
  },
  {
    id: 'beef-meat-products-beef-rib-eye-local',
    name: 'Beef Rib Eye, Local',
    category: COMMODITY_CATEGORIES.BEEF_MEAT_PRODUCTS,
    unit: 'kg',
    type: 'Beef Rib Eye, Local',
  },
  {
    id: 'beef-meat-products-beef-rib-set-imported',
    name: 'Beef Rib Set, Imported',
    category: COMMODITY_CATEGORIES.BEEF_MEAT_PRODUCTS,
    unit: 'kg',
    type: 'Beef Rib Set, Imported',
  },
  {
    id: 'beef-meat-products-beef-rib-set-local',
    name: 'Beef Rib Set, Local',
    category: COMMODITY_CATEGORIES.BEEF_MEAT_PRODUCTS,
    unit: 'kg',
    type: 'Beef Rib Set, Local',
  },
  {
    id: 'beef-meat-products-beef-rump-imported',
    name: 'Beef Rump, Imported',
    category: COMMODITY_CATEGORIES.BEEF_MEAT_PRODUCTS,
    unit: 'kg',
    type: 'Beef Rump, Imported',
  },
  {
    id: 'beef-meat-products-beef-rump-local-lean-meat-tapadera',
    name: 'Beef Rump, Local',
    category: COMMODITY_CATEGORIES.BEEF_MEAT_PRODUCTS,
    unit: 'kg',
    type: 'Beef Rump, Local',
    specification: 'Lean Meat/ Tapadera',
  },
  {
    id: 'beef-meat-products-beef-short-ribs-imported',
    name: 'Beef Short Ribs, Imported',
    category: COMMODITY_CATEGORIES.BEEF_MEAT_PRODUCTS,
    unit: 'kg',
    type: 'Beef Short Ribs, Imported',
  },
  {
    id: 'beef-meat-products-beef-short-ribs-local',
    name: 'Beef Short Ribs, Local',
    category: COMMODITY_CATEGORIES.BEEF_MEAT_PRODUCTS,
    unit: 'kg',
    type: 'Beef Short Ribs, Local',
  },
  {
    id: 'beef-meat-products-beef-sirloin-imported',
    name: 'Beef Sirloin, Imported',
    category: COMMODITY_CATEGORIES.BEEF_MEAT_PRODUCTS,
    unit: 'kg',
    type: 'Beef Sirloin, Imported',
  },
  {
    id: 'beef-meat-products-beef-sirloin-local',
    name: 'Beef Sirloin, Local',
    category: COMMODITY_CATEGORIES.BEEF_MEAT_PRODUCTS,
    unit: 'kg',
    type: 'Beef Sirloin, Local',
  },
  {
    id: 'beef-meat-products-beef-striploin-imported',
    name: 'Beef Striploin, Imported',
    category: COMMODITY_CATEGORIES.BEEF_MEAT_PRODUCTS,
    unit: 'kg',
    type: 'Beef Striploin, Imported',
  },
  {
    id: 'beef-meat-products-beef-striploin-local',
    name: 'Beef Striploin, Local',
    category: COMMODITY_CATEGORIES.BEEF_MEAT_PRODUCTS,
    unit: 'kg',
    type: 'Beef Striploin, Local',
  },
  {
    id: 'beef-meat-products-beef-tenderloin-imported',
    name: 'Beef Tenderloin, Imported',
    category: COMMODITY_CATEGORIES.BEEF_MEAT_PRODUCTS,
    unit: 'kg',
    type: 'Beef Tenderloin, Imported',
  },
  {
    id: 'beef-meat-products-beef-tenderloin-local',
    name: 'Beef Tenderloin, Local',
    category: COMMODITY_CATEGORIES.BEEF_MEAT_PRODUCTS,
    unit: 'kg',
    type: 'Beef Tenderloin, Local',
  },
  {
    id: 'beef-meat-products-beef-tongue-imported',
    name: 'Beef Tongue, Imported',
    category: COMMODITY_CATEGORIES.BEEF_MEAT_PRODUCTS,
    unit: 'kg',
    type: 'Beef Tongue, Imported',
  },
  {
    id: 'beef-meat-products-beef-tongue-local',
    name: 'Beef Tongue, Local',
    category: COMMODITY_CATEGORIES.BEEF_MEAT_PRODUCTS,
    unit: 'kg',
    type: 'Beef Tongue, Local',
  },
  {
    id: 'corn-products-corn-white-cob-glutinous',
    name: 'Corn (White)',
    category: COMMODITY_CATEGORIES.CORN_PRODUCTS,
    unit: 'kg',
    type: 'Corn (White)',
    specification: 'Cob, Glutinous',
  },
  {
    id: 'corn-products-corn-yellow-cob-sweet-corn',
    name: 'Corn (Yellow)',
    category: COMMODITY_CATEGORIES.CORN_PRODUCTS,
    unit: 'kg',
    type: 'Corn (Yellow)',
    specification: 'Cob, Sweet Corn',
  },
  {
    id: 'corn-products-corn-cracked-yellow-feed-grade',
    name: 'Corn Cracked (Yellow, Feed Grade)',
    category: COMMODITY_CATEGORIES.CORN_PRODUCTS,
    unit: 'kg',
    type: 'Corn Cracked (Yellow, Feed Grade)',
  },
  {
    id: 'corn-products-corn-grits-feed-grade',
    name: 'Corn Grits (Feed Grade)',
    category: COMMODITY_CATEGORIES.CORN_PRODUCTS,
    unit: 'kg',
    type: 'Corn Grits (Feed Grade)',
  },
  {
    id: 'corn-products-corn-grits-white-food-grade',
    name: 'Corn Grits (White, Food Grade)',
    category: COMMODITY_CATEGORIES.CORN_PRODUCTS,
    unit: 'kg',
    type: 'Corn Grits (White, Food Grade)',
  },
  {
    id: 'corn-products-corn-grits-yellow-food-grade',
    name: 'Corn Grits (Yellow, Food Grade)',
    category: COMMODITY_CATEGORIES.CORN_PRODUCTS,
    unit: 'kg',
    type: 'Corn Grits (Yellow, Food Grade)',
  },
  {
    id: 'fish-products-alumahan-indian-mackerel-medium-4-6-pcskg',
    name: 'Alumahan (Indian Mackerel)',
    category: COMMODITY_CATEGORIES.FISH_PRODUCTS,
    unit: 'kg',
    type: 'Alumahan (Indian Mackerel)',
    specification: 'Medium (4-6 pcs/kg)',
  },
  {
    id: 'fish-products-bangus-large-large-1-2-pcs',
    name: 'Bangus, Large',
    category: COMMODITY_CATEGORIES.FISH_PRODUCTS,
    unit: 'kg',
    type: 'Bangus, Large',
    specification: 'Large (1-2 pcs)',
  },
  {
    id: 'fish-products-bangus-medium-medium-3-4-pcskg',
    name: 'Bangus, Medium',
    category: COMMODITY_CATEGORIES.FISH_PRODUCTS,
    unit: 'kg',
    type: 'Bangus, Medium',
    specification: 'Medium (3-4 pcs/kg)',
  },
  {
    id: 'fish-products-bonito-frigate-tuna',
    name: 'Bonito (Frigate Tuna)',
    category: COMMODITY_CATEGORIES.FISH_PRODUCTS,
    unit: 'kg',
    type: 'Bonito (Frigate Tuna)',
  },
  {
    id: 'fish-products-galunggong-imported-male-medium-12-14-pcskg',
    name: 'Galunggong, Imported',
    category: COMMODITY_CATEGORIES.FISH_PRODUCTS,
    unit: 'kg',
    type: 'Galunggong, Imported',
    specification: 'Male, Medium (12-14 pcs/kg)',
  },
  {
    id: 'fish-products-galunggong-local-male-medium-12-14-pcskg',
    name: 'Galunggong, Local',
    category: COMMODITY_CATEGORIES.FISH_PRODUCTS,
    unit: 'kg',
    type: 'Galunggong, Local',
    specification: 'Male, Medium (12-14 pcs/kg)',
  },
  {
    id: 'fish-products-mackerel-imported-frozen-whole-round',
    name: 'Mackerel, Imported',
    category: COMMODITY_CATEGORIES.FISH_PRODUCTS,
    unit: 'kg',
    type: 'Mackerel, Imported',
    specification: 'Frozen, Whole Round',
  },
  {
    id: 'fish-products-mackerel-local-fresh-whole-round',
    name: 'Mackerel, Local',
    category: COMMODITY_CATEGORIES.FISH_PRODUCTS,
    unit: 'kg',
    type: 'Mackerel, Local',
    specification: 'Fresh, Whole Round',
  },
  {
    id: 'fish-products-pampano-imported',
    name: 'Pampano, Imported',
    category: COMMODITY_CATEGORIES.FISH_PRODUCTS,
    unit: 'kg',
    type: 'Pampano, Imported',
  },
  {
    id: 'fish-products-pampano-local',
    name: 'Pampano, Local',
    category: COMMODITY_CATEGORIES.FISH_PRODUCTS,
    unit: 'kg',
    type: 'Pampano, Local',
  },
  {
    id: 'fish-products-salmon-belly-imported',
    name: 'Salmon Belly, Imported',
    category: COMMODITY_CATEGORIES.FISH_PRODUCTS,
    unit: 'kg',
    type: 'Salmon Belly, Imported',
  },
  {
    id: 'fish-products-salmon-belly-local',
    name: 'Salmon Belly, Local',
    category: COMMODITY_CATEGORIES.FISH_PRODUCTS,
    unit: 'kg',
    type: 'Salmon Belly, Local',
  },
  {
    id: 'fish-products-salmon-head-imported',
    name: 'Salmon Head, Imported',
    category: COMMODITY_CATEGORIES.FISH_PRODUCTS,
    unit: 'kg',
    type: 'Salmon Head, Imported',
  },
  {
    id: 'fish-products-salmon-head-local',
    name: 'Salmon Head, Local',
    category: COMMODITY_CATEGORIES.FISH_PRODUCTS,
    unit: 'kg',
    type: 'Salmon Head, Local',
  },
  {
    id: 'fish-products-sardines-tamban',
    name: 'Sardines (Tamban)',
    category: COMMODITY_CATEGORIES.FISH_PRODUCTS,
    unit: 'kg',
    type: 'Sardines (Tamban)',
  },
  {
    id: 'fish-products-squid-pusit-bisaya-local-medium',
    name: 'Squid (Pusit Bisaya), Local',
    category: COMMODITY_CATEGORIES.FISH_PRODUCTS,
    unit: 'kg',
    type: 'Squid (Pusit Bisaya), Local',
    specification: 'Medium',
  },
  {
    id: 'fish-products-squid-imported',
    name: 'Squid, Imported',
    category: COMMODITY_CATEGORIES.FISH_PRODUCTS,
    unit: 'kg',
    type: 'Squid, Imported',
  },
  {
    id: 'fish-products-tambakol-yellow-fin-tuna-imported-medium-frozen',
    name: 'Tambakol (Yellow-Fin Tuna), Imported',
    category: COMMODITY_CATEGORIES.FISH_PRODUCTS,
    unit: 'kg',
    type: 'Tambakol (Yellow-Fin Tuna), Imported',
    specification: 'Medium, Frozen',
  },
  {
    id: 'fish-products-tambakol-yellow-fin-tuna-local-medium-fresh-or-chilled',
    name: 'Tambakol (Yellow-Fin Tuna), Local',
    category: COMMODITY_CATEGORIES.FISH_PRODUCTS,
    unit: 'kg',
    type: 'Tambakol (Yellow-Fin Tuna), Local',
    specification: 'Medium, Fresh or Chilled',
  },
  {
    id: 'fish-products-tilapia-medium-5-6-pcskg',
    name: 'Tilapia',
    category: COMMODITY_CATEGORIES.FISH_PRODUCTS,
    unit: 'kg',
    type: 'Tilapia',
    specification: 'Medium (5-6 pcs/kg)',
  },
  {
    id: 'fruits-avocado',
    name: 'Avocado',
    category: COMMODITY_CATEGORIES.FRUITS,
    unit: 'kg',
    type: 'Avocado',
  },
  {
    id: 'fruits-banana-lakatan-8-10-pcskg',
    name: 'Banana (Lakatan)',
    category: COMMODITY_CATEGORIES.FRUITS,
    unit: 'kg',
    type: 'Banana (Lakatan)',
    specification: '8-10 pcs/kg',
  },
  {
    id: 'fruits-banana-latundan-10-12-pcskg',
    name: 'Banana (Latundan)',
    category: COMMODITY_CATEGORIES.FRUITS,
    unit: 'kg',
    type: 'Banana (Latundan)',
    specification: '10-12 pcs/kg',
  },
  {
    id: 'fruits-banana-saba',
    name: 'Banana (Saba)',
    category: COMMODITY_CATEGORIES.FRUITS,
    unit: 'kg',
    type: 'Banana (Saba)',
  },
  {
    id: 'fruits-calamansi',
    name: 'Calamansi',
    category: COMMODITY_CATEGORIES.FRUITS,
    unit: 'kg',
    type: 'Calamansi',
  },
  {
    id: 'fruits-mango-carabao-ripe-3-4-pcskg',
    name: 'Mango (Carabao)',
    category: COMMODITY_CATEGORIES.FRUITS,
    unit: 'kg',
    type: 'Mango (Carabao)',
    specification: 'Ripe, 3-4 pcs/kg',
  },
  {
    id: 'fruits-melon',
    name: 'Melon',
    category: COMMODITY_CATEGORIES.FRUITS,
    unit: 'kg',
    type: 'Melon',
  },
  {
    id: 'fruits-papaya-solo-ripe-2-3-pcskg',
    name: 'Papaya',
    category: COMMODITY_CATEGORIES.FRUITS,
    unit: 'kg',
    type: 'Papaya',
    specification: 'Solo, Ripe, 2-3 pcs/kg',
  },
  {
    id: 'fruits-pomelo',
    name: 'Pomelo',
    category: COMMODITY_CATEGORIES.FRUITS,
    unit: 'kg',
    type: 'Pomelo',
  },
  {
    id: 'fruits-watermelon',
    name: 'Watermelon',
    category: COMMODITY_CATEGORIES.FRUITS,
    unit: 'kg',
    type: 'Watermelon',
  },
  {
    id: 'highland-vegetables-bell-pepper-green-imported',
    name: 'Bell Pepper (Green), Imported',
    category: COMMODITY_CATEGORIES.HIGHLAND_VEGETABLES,
    unit: 'kg',
    type: 'Bell Pepper (Green), Imported',
  },
  {
    id: 'highland-vegetables-bell-pepper-green-local-medium-151-250gmpc',
    name: 'Bell Pepper (Green), Local',
    category: COMMODITY_CATEGORIES.HIGHLAND_VEGETABLES,
    unit: 'kg',
    type: 'Bell Pepper (Green), Local',
    specification: 'Medium (151-250gm/pc)',
  },
  {
    id: 'highland-vegetables-bell-pepper-red-imported',
    name: 'Bell Pepper (Red), Imported',
    category: COMMODITY_CATEGORIES.HIGHLAND_VEGETABLES,
    unit: 'kg',
    type: 'Bell Pepper (Red), Imported',
  },
  {
    id: 'highland-vegetables-bell-pepper-red-local-medium-151-250gmpc',
    name: 'Bell Pepper (Red), Local',
    category: COMMODITY_CATEGORIES.HIGHLAND_VEGETABLES,
    unit: 'kg',
    type: 'Bell Pepper (Red), Local',
    specification: 'Medium (151-250gm/pc)',
  },
  {
    id: 'highland-vegetables-broccoli-imported',
    name: 'Broccoli, Imported',
    category: COMMODITY_CATEGORIES.HIGHLAND_VEGETABLES,
    unit: 'kg',
    type: 'Broccoli, Imported',
  },
  {
    id: 'highland-vegetables-broccoli-local-medium-8-10-cm-diameterbunch-hd',
    name: 'Broccoli, Local',
    category: COMMODITY_CATEGORIES.HIGHLAND_VEGETABLES,
    unit: 'kg',
    type: 'Broccoli, Local',
    specification: 'Medium (8-10 cm diameter/bunch hd)',
  },
  {
    id: 'highland-vegetables-cabbage-rare-ball-510-gm---1-kghead',
    name: 'Cabbage (Rare Ball)',
    category: COMMODITY_CATEGORIES.HIGHLAND_VEGETABLES,
    unit: 'kg',
    type: 'Cabbage (Rare Ball)',
    specification: '510 gm - 1 kg/head',
  },
  {
    id: 'highland-vegetables-cabbage-scorpio-750-gm---1-kghead',
    name: 'Cabbage (Scorpio)',
    category: COMMODITY_CATEGORIES.HIGHLAND_VEGETABLES,
    unit: 'kg',
    type: 'Cabbage (Scorpio)',
    specification: '750 gm - 1 kg/head',
  },
  {
    id: 'highland-vegetables-cabbage-wonder-ball-510-gm---1-kghead',
    name: 'Cabbage (Wonder Ball)',
    category: COMMODITY_CATEGORIES.HIGHLAND_VEGETABLES,
    unit: 'kg',
    type: 'Cabbage (Wonder Ball)',
    specification: '510 gm - 1 kg/head',
  },
  {
    id: 'highland-vegetables-cabbage-imported',
    name: 'Cabbage, Imported',
    category: COMMODITY_CATEGORIES.HIGHLAND_VEGETABLES,
    unit: 'kg',
    type: 'Cabbage, Imported',
  },
  {
    id: 'highland-vegetables-carrots-imported',
    name: 'Carrots, Imported',
    category: COMMODITY_CATEGORIES.HIGHLAND_VEGETABLES,
    unit: 'kg',
    type: 'Carrots, Imported',
  },
  {
    id: 'highland-vegetables-carrots-local-8-10-pcskg',
    name: 'Carrots, Local',
    category: COMMODITY_CATEGORIES.HIGHLAND_VEGETABLES,
    unit: 'kg',
    type: 'Carrots, Local',
    specification: '8-10 pcs/kg',
  },
  {
    id: 'highland-vegetables-cauliflower-imported',
    name: 'Cauliflower, Imported',
    category: COMMODITY_CATEGORIES.HIGHLAND_VEGETABLES,
    unit: 'kg',
    type: 'Cauliflower, Imported',
  },
  {
    id: 'highland-vegetables-cauliflower-local-medium-8-10-cm-diameterbunch-hd',
    name: 'Cauliflower, Local',
    category: COMMODITY_CATEGORIES.HIGHLAND_VEGETABLES,
    unit: 'kg',
    type: 'Cauliflower, Local',
    specification: 'Medium (8-10 cm diameter/bunch hd)',
  },
  {
    id: 'highland-vegetables-celery-medium-501-800-g',
    name: 'Celery',
    category: COMMODITY_CATEGORIES.HIGHLAND_VEGETABLES,
    unit: 'kg',
    type: 'Celery',
    specification: 'Medium (501-800 g)',
  },
  {
    id: 'highland-vegetables-chayote-medium-301-400-g',
    name: 'Chayote',
    category: COMMODITY_CATEGORIES.HIGHLAND_VEGETABLES,
    unit: 'kg',
    type: 'Chayote',
    specification: 'Medium (301-400 g)',
  },
  {
    id: 'highland-vegetables-habichuelasbaguio-beans-local',
    name: 'Habichuelas/Baguio Beans, Local',
    category: COMMODITY_CATEGORIES.HIGHLAND_VEGETABLES,
    unit: 'kg',
    type: 'Habichuelas/Baguio Beans, Local',
  },
  {
    id: 'highland-vegetables-lettuce-green-ice',
    name: 'Lettuce (Green Ice)',
    category: COMMODITY_CATEGORIES.HIGHLAND_VEGETABLES,
    unit: 'kg',
    type: 'Lettuce (Green Ice)',
  },
  {
    id: 'highland-vegetables-lettuce-iceberg-medium-301-450-cm-diameterbunch-hd',
    name: 'Lettuce (Iceberg)',
    category: COMMODITY_CATEGORIES.HIGHLAND_VEGETABLES,
    unit: 'kg',
    type: 'Lettuce (Iceberg)',
    specification: 'Medium (301-450 cm diameter/bunch hd)',
  },
  {
    id: 'highland-vegetables-lettuce-romaine',
    name: 'Lettuce (Romaine)',
    category: COMMODITY_CATEGORIES.HIGHLAND_VEGETABLES,
    unit: 'kg',
    type: 'Lettuce (Romaine)',
  },
  {
    id: 'highland-vegetables-lettuce-imported',
    name: 'Lettuce, Imported',
    category: COMMODITY_CATEGORIES.HIGHLAND_VEGETABLES,
    unit: 'kg',
    type: 'Lettuce, Imported',
  },
  {
    id: 'highland-vegetables-pechay-baguio',
    name: 'Pechay Baguio',
    category: COMMODITY_CATEGORIES.HIGHLAND_VEGETABLES,
    unit: 'kg',
    type: 'Pechay Baguio',
  },
  {
    id: 'highland-vegetables-white-potato-imported',
    name: 'White Potato, Imported',
    category: COMMODITY_CATEGORIES.HIGHLAND_VEGETABLES,
    unit: 'kg',
    type: 'White Potato, Imported',
  },
  {
    id: 'highland-vegetables-white-potato-local-10-12-pcskg',
    name: 'White Potato, Local',
    category: COMMODITY_CATEGORIES.HIGHLAND_VEGETABLES,
    unit: 'kg',
    type: 'White Potato, Local',
    specification: '10-12 pcs/kg',
  },
  {
    id: 'imported-commercial-rice-premium-5-broken',
    name: 'Premium',
    category: COMMODITY_CATEGORIES.IMPORTED_COMMERCIAL_RICE,
    unit: 'kg',
    type: 'Premium',
    specification: '5% broken',
  },
  {
    id: 'imported-commercial-rice-regular-milled-20-40-bran-streak',
    name: 'Regular Milled',
    category: COMMODITY_CATEGORIES.IMPORTED_COMMERCIAL_RICE,
    unit: 'kg',
    type: 'Regular Milled',
    specification: '20-40% bran streak',
  },
  {
    id: 'imported-commercial-rice-special-rice-white-rice',
    name: 'Special Rice',
    category: COMMODITY_CATEGORIES.IMPORTED_COMMERCIAL_RICE,
    unit: 'kg',
    type: 'Special Rice',
    specification: 'White Rice',
  },
  {
    id: 'imported-commercial-rice-well-milled-1-19-bran-streak',
    name: 'Well Milled',
    category: COMMODITY_CATEGORIES.IMPORTED_COMMERCIAL_RICE,
    unit: 'kg',
    type: 'Well Milled',
    specification: '1-19% bran streak',
  },
  {
    id: 'kadiwa-rice-for-all-p20-benteng-bigas-meron-na',
    name: 'P20 Benteng Bigas Meron Na',
    category: COMMODITY_CATEGORIES.KADIWA_RICE_FOR_ALL,
    unit: 'kg',
    type: 'P20 Benteng Bigas Meron Na',
  },
  {
    id: 'kadiwa-rice-for-all-premium-rfa5',
    name: 'Premium (RFA5)',
    category: COMMODITY_CATEGORIES.KADIWA_RICE_FOR_ALL,
    unit: 'kg',
    type: 'Premium (RFA5)',
  },
  {
    id: 'kadiwa-rice-for-all-regular-milled-rfa100',
    name: 'Regular Milled (RFA100)',
    category: COMMODITY_CATEGORIES.KADIWA_RICE_FOR_ALL,
    unit: 'kg',
    type: 'Regular Milled (RFA100)',
  },
  {
    id: 'kadiwa-rice-for-all-well-milled-rfa25',
    name: 'Well Milled (RFA25)',
    category: COMMODITY_CATEGORIES.KADIWA_RICE_FOR_ALL,
    unit: 'kg',
    type: 'Well Milled (RFA25)',
  },
  {
    id: 'livestock-and-poultry-products-frozen-kasim-per-kg',
    name: 'Frozen Kasim',
    category: COMMODITY_CATEGORIES.LIVESTOCK_AND_POULTRY_PRODUCTS,
    unit: 'kg',
    type: 'Frozen Kasim',
    specification: 'per kg',
  },
  {
    id: 'livestock-and-poultry-products-frozen-liempo-per-kg',
    name: 'Frozen Liempo',
    category: COMMODITY_CATEGORIES.LIVESTOCK_AND_POULTRY_PRODUCTS,
    unit: 'kg',
    type: 'Frozen Liempo',
    specification: 'per kg',
  },
  {
    id: 'local-commercial-rice-premium-5-broken',
    name: 'Premium',
    category: COMMODITY_CATEGORIES.LOCAL_COMMERCIAL_RICE,
    unit: 'kg',
    type: 'Premium',
    specification: '5% broken',
  },
  {
    id: 'local-commercial-rice-regular-milled-20-40-bran-streak',
    name: 'Regular Milled',
    category: COMMODITY_CATEGORIES.LOCAL_COMMERCIAL_RICE,
    unit: 'kg',
    type: 'Regular Milled',
    specification: '20-40% bran streak',
  },
  {
    id: 'local-commercial-rice-special-rice-white-rice',
    name: 'Special Rice',
    category: COMMODITY_CATEGORIES.LOCAL_COMMERCIAL_RICE,
    unit: 'kg',
    type: 'Special Rice',
    specification: 'White Rice',
  },
  {
    id: 'local-commercial-rice-well-milled-1-19-bran-streak',
    name: 'Well Milled',
    category: COMMODITY_CATEGORIES.LOCAL_COMMERCIAL_RICE,
    unit: 'kg',
    type: 'Well Milled',
    specification: '1-19% bran streak',
  },
  {
    id: 'lowland-vegetables-ampalaya-4-5-pcskg',
    name: 'Ampalaya',
    category: COMMODITY_CATEGORIES.LOWLAND_VEGETABLES,
    unit: 'kg',
    type: 'Ampalaya',
    specification: '4-5 pcs/kg',
  },
  {
    id: 'lowland-vegetables-chilli-green-local-habapanigang',
    name: 'Chilli (Green), Local',
    category: COMMODITY_CATEGORIES.LOWLAND_VEGETABLES,
    unit: 'kg',
    type: 'Chilli (Green), Local',
    specification: 'Haba/Panigang',
  },
  {
    id: 'lowland-vegetables-eggplant-3-4-small-bundles',
    name: 'Eggplant',
    category: COMMODITY_CATEGORIES.LOWLAND_VEGETABLES,
    unit: 'kg',
    type: 'Eggplant',
    specification: '3-4 Small Bundles',
  },
  {
    id: 'lowland-vegetables-native-pechay-3-4-small-bundles',
    name: 'Native Pechay',
    category: COMMODITY_CATEGORIES.LOWLAND_VEGETABLES,
    unit: 'kg',
    type: 'Native Pechay',
    specification: '3-4 Small Bundles',
  },
  {
    id: 'lowland-vegetables-pechay-tagalog-3-4-small-bundles',
    name: 'Pechay Tagalog',
    category: COMMODITY_CATEGORIES.LOWLAND_VEGETABLES,
    unit: 'kg',
    type: 'Pechay Tagalog',
    specification: '3-4 Small Bundles',
  },
  {
    id: 'lowland-vegetables-pole-sitao-3-4-small-bundles',
    name: 'Pole Sitao',
    category: COMMODITY_CATEGORIES.LOWLAND_VEGETABLES,
    unit: 'kg',
    type: 'Pole Sitao',
    specification: '3-4 Small Bundles',
  },
  {
    id: 'lowland-vegetables-squash-suprema-variety',
    name: 'Squash',
    category: COMMODITY_CATEGORIES.LOWLAND_VEGETABLES,
    unit: 'kg',
    type: 'Squash',
    specification: 'Suprema Variety',
  },
  {
    id: 'lowland-vegetables-tomato-15-18-pcskg',
    name: 'Tomato',
    category: COMMODITY_CATEGORIES.LOWLAND_VEGETABLES,
    unit: 'kg',
    type: 'Tomato',
    specification: '15-18 pcs/kg',
  },
  {
    id: 'other-basic-commodities-cooking-oil-coconut-1-literbottle',
    name: 'Cooking Oil (Coconut)',
    category: COMMODITY_CATEGORIES.OTHER_BASIC_COMMODITIES,
    unit: 'L',
    type: 'Cooking Oil (Coconut)',
    specification: '1 Liter/bottle',
  },
  {
    id: 'other-basic-commodities-cooking-oil-coconut-350-mlbottle',
    name: 'Cooking Oil (Coconut)',
    category: COMMODITY_CATEGORIES.OTHER_BASIC_COMMODITIES,
    unit: 'L',
    type: 'Cooking Oil (Coconut)',
    specification: '350 ml/bottle',
  },
  {
    id: 'other-basic-commodities-cooking-oil-minola-1000-mlbottle',
    name: 'Cooking Oil (Minola)',
    category: COMMODITY_CATEGORIES.OTHER_BASIC_COMMODITIES,
    unit: 'L',
    type: 'Cooking Oil (Minola)',
    specification: '1,000 ml/bottle',
  },
  {
    id: 'other-basic-commodities-cooking-oil-minola-500-mlbottle',
    name: 'Cooking Oil (Minola)',
    category: COMMODITY_CATEGORIES.OTHER_BASIC_COMMODITIES,
    unit: 'L',
    type: 'Cooking Oil (Minola)',
    specification: '500 ml/bottle',
  },
  {
    id: 'other-basic-commodities-cooking-oil-palm-olein-jolly-brand-1000-mlbottle',
    name: 'Cooking Oil (Palm Olein, Jolly Brand)',
    category: COMMODITY_CATEGORIES.OTHER_BASIC_COMMODITIES,
    unit: 'L',
    type: 'Cooking Oil (Palm Olein, Jolly Brand)',
    specification: '1,000 ml/bottle',
  },
  {
    id: 'other-basic-commodities-cooking-oil-palm-1-literbottle',
    name: 'Cooking Oil (Palm)',
    category: COMMODITY_CATEGORIES.OTHER_BASIC_COMMODITIES,
    unit: 'L',
    type: 'Cooking Oil (Palm)',
    specification: '1 Liter/bottle',
  },
  {
    id: 'other-basic-commodities-cooking-oil-palm-350-mlbottle',
    name: 'Cooking Oil (Palm)',
    category: COMMODITY_CATEGORIES.OTHER_BASIC_COMMODITIES,
    unit: 'L',
    type: 'Cooking Oil (Palm)',
    specification: '350 ml/bottle',
  },
  {
    id: 'other-basic-commodities-cooking-oil-palm-375-mlbottle',
    name: 'Cooking Oil (Palm)',
    category: COMMODITY_CATEGORIES.OTHER_BASIC_COMMODITIES,
    unit: 'L',
    type: 'Cooking Oil (Palm)',
    specification: '375 ml/bottle',
  },
  {
    id: 'other-basic-commodities-cooking-oil-palm-750-mlbottle',
    name: 'Cooking Oil (Palm)',
    category: COMMODITY_CATEGORIES.OTHER_BASIC_COMMODITIES,
    unit: 'L',
    type: 'Cooking Oil (Palm)',
    specification: '750 ml/bottle',
  },
  {
    id: 'other-basic-commodities-cooking-oil-spring-1000-mlbottle',
    name: 'Cooking Oil (Spring)',
    category: COMMODITY_CATEGORIES.OTHER_BASIC_COMMODITIES,
    unit: 'L',
    type: 'Cooking Oil (Spring)',
    specification: '1,000 ml/bottle',
  },
  {
    id: 'other-basic-commodities-cooking-oil-spring-500-mlbottle',
    name: 'Cooking Oil (Spring)',
    category: COMMODITY_CATEGORIES.OTHER_BASIC_COMMODITIES,
    unit: 'L',
    type: 'Cooking Oil (Spring)',
    specification: '500 ml/bottle',
  },
  {
    id: 'other-basic-commodities-salt-iodized',
    name: 'Salt (Iodized)',
    category: COMMODITY_CATEGORIES.OTHER_BASIC_COMMODITIES,
    unit: 'kg',
    type: 'Salt (Iodized)',
  },
  {
    id: 'other-basic-commodities-salt-rock',
    name: 'Salt (Rock)',
    category: COMMODITY_CATEGORIES.OTHER_BASIC_COMMODITIES,
    unit: 'kg',
    type: 'Salt (Rock)',
  },
  {
    id: 'other-basic-commodities-sugar-brown',
    name: 'Sugar (Brown)',
    category: COMMODITY_CATEGORIES.OTHER_BASIC_COMMODITIES,
    unit: 'kg',
    type: 'Sugar (Brown)',
  },
  {
    id: 'other-basic-commodities-sugar-refined',
    name: 'Sugar (Refined)',
    category: COMMODITY_CATEGORIES.OTHER_BASIC_COMMODITIES,
    unit: 'kg',
    type: 'Sugar (Refined)',
  },
  {
    id: 'other-basic-commodities-sugar-washed',
    name: 'Sugar (Washed)',
    category: COMMODITY_CATEGORIES.OTHER_BASIC_COMMODITIES,
    unit: 'kg',
    type: 'Sugar (Washed)',
  },
  {
    id: 'other-livestock-meat-products-carabeef-forequarter-imported',
    name: 'Carabeef Forequarter, Imported',
    category: COMMODITY_CATEGORIES.OTHER_LIVESTOCK_MEAT_PRODUCTS,
    unit: 'kg',
    type: 'Carabeef Forequarter, Imported',
  },
  {
    id: 'other-livestock-meat-products-carabeef-forequarter-local',
    name: 'Carabeef Forequarter, Local',
    category: COMMODITY_CATEGORIES.OTHER_LIVESTOCK_MEAT_PRODUCTS,
    unit: 'kg',
    type: 'Carabeef Forequarter, Local',
  },
  {
    id: 'other-livestock-meat-products-carabeef-meat-imported',
    name: 'Carabeef Meat, Imported',
    category: COMMODITY_CATEGORIES.OTHER_LIVESTOCK_MEAT_PRODUCTS,
    unit: 'kg',
    type: 'Carabeef Meat, Imported',
  },
  {
    id: 'other-livestock-meat-products-carabeef-meat-local',
    name: 'Carabeef Meat, Local',
    category: COMMODITY_CATEGORIES.OTHER_LIVESTOCK_MEAT_PRODUCTS,
    unit: 'kg',
    type: 'Carabeef Meat, Local',
  },
  {
    id: 'other-livestock-meat-products-carabeef-rump-steak-imported',
    name: 'Carabeef Rump Steak, Imported',
    category: COMMODITY_CATEGORIES.OTHER_LIVESTOCK_MEAT_PRODUCTS,
    unit: 'kg',
    type: 'Carabeef Rump Steak, Imported',
  },
  {
    id: 'other-livestock-meat-products-carabeef-rump-steak-local',
    name: 'Carabeef Rump Steak, Local',
    category: COMMODITY_CATEGORIES.OTHER_LIVESTOCK_MEAT_PRODUCTS,
    unit: 'kg',
    type: 'Carabeef Rump Steak, Local',
  },
  {
    id: 'other-livestock-meat-products-carabeef-trimmings-imported',
    name: 'Carabeef Trimmings, Imported',
    category: COMMODITY_CATEGORIES.OTHER_LIVESTOCK_MEAT_PRODUCTS,
    unit: 'kg',
    type: 'Carabeef Trimmings, Imported',
  },
  {
    id: 'other-livestock-meat-products-carabeef-trimmings-local',
    name: 'Carabeef Trimmings, Local',
    category: COMMODITY_CATEGORIES.OTHER_LIVESTOCK_MEAT_PRODUCTS,
    unit: 'kg',
    type: 'Carabeef Trimmings, Local',
  },
  {
    id: 'other-livestock-meat-products-lamb-meat',
    name: 'Lamb Meat',
    category: COMMODITY_CATEGORIES.OTHER_LIVESTOCK_MEAT_PRODUCTS,
    unit: 'kg',
    type: 'Lamb Meat',
  },
  {
    id: 'pork-meat-products-pork-belly-liempo-imported',
    name: 'Pork Belly (Liempo), Imported',
    category: COMMODITY_CATEGORIES.PORK_MEAT_PRODUCTS,
    unit: 'kg',
    type: 'Pork Belly (Liempo), Imported',
  },
  {
    id: 'pork-meat-products-pork-belly-liempo-local',
    name: 'Pork Belly (Liempo), Local',
    category: COMMODITY_CATEGORIES.PORK_MEAT_PRODUCTS,
    unit: 'kg',
    type: 'Pork Belly (Liempo), Local',
  },
  {
    id: 'pork-meat-products-pork-boston-shoulder-imported',
    name: 'Pork Boston Shoulder, Imported',
    category: COMMODITY_CATEGORIES.PORK_MEAT_PRODUCTS,
    unit: 'kg',
    type: 'Pork Boston Shoulder, Imported',
  },
  {
    id: 'pork-meat-products-pork-boston-shoulder-local',
    name: 'Pork Boston Shoulder, Local',
    category: COMMODITY_CATEGORIES.PORK_MEAT_PRODUCTS,
    unit: 'kg',
    type: 'Pork Boston Shoulder, Local',
  },
  {
    id: 'pork-meat-products-pork-chop-imported',
    name: 'Pork Chop, Imported',
    category: COMMODITY_CATEGORIES.PORK_MEAT_PRODUCTS,
    unit: 'kg',
    type: 'Pork Chop, Imported',
  },
  {
    id: 'pork-meat-products-pork-chop-local',
    name: 'Pork Chop, Local',
    category: COMMODITY_CATEGORIES.PORK_MEAT_PRODUCTS,
    unit: 'kg',
    type: 'Pork Chop, Local',
  },
  {
    id: 'pork-meat-products-pork-fore-shank-imported',
    name: 'Pork Fore Shank, Imported',
    category: COMMODITY_CATEGORIES.PORK_MEAT_PRODUCTS,
    unit: 'kg',
    type: 'Pork Fore Shank, Imported',
  },
  {
    id: 'pork-meat-products-pork-fore-shank-local',
    name: 'Pork Fore Shank, Local',
    category: COMMODITY_CATEGORIES.PORK_MEAT_PRODUCTS,
    unit: 'kg',
    type: 'Pork Fore Shank, Local',
  },
  {
    id: 'pork-meat-products-pork-head-imported',
    name: 'Pork Head, Imported',
    category: COMMODITY_CATEGORIES.PORK_MEAT_PRODUCTS,
    unit: 'kg',
    type: 'Pork Head, Imported',
  },
  {
    id: 'pork-meat-products-pork-head-local',
    name: 'Pork Head, Local',
    category: COMMODITY_CATEGORIES.PORK_MEAT_PRODUCTS,
    unit: 'kg',
    type: 'Pork Head, Local',
  },
  {
    id: 'pork-meat-products-pork-hind-leg-pigue-imported',
    name: 'Pork Hind Leg (Pigue), Imported',
    category: COMMODITY_CATEGORIES.PORK_MEAT_PRODUCTS,
    unit: 'kg',
    type: 'Pork Hind Leg (Pigue), Imported',
  },
  {
    id: 'pork-meat-products-pork-hind-leg-pigue-local',
    name: 'Pork Hind Leg (Pigue), Local',
    category: COMMODITY_CATEGORIES.PORK_MEAT_PRODUCTS,
    unit: 'kg',
    type: 'Pork Hind Leg (Pigue), Local',
  },
  {
    id: 'pork-meat-products-pork-hind-shank-imported',
    name: 'Pork Hind Shank, Imported',
    category: COMMODITY_CATEGORIES.PORK_MEAT_PRODUCTS,
    unit: 'kg',
    type: 'Pork Hind Shank, Imported',
  },
  {
    id: 'pork-meat-products-pork-hind-shank-local',
    name: 'Pork Hind Shank, Local',
    category: COMMODITY_CATEGORIES.PORK_MEAT_PRODUCTS,
    unit: 'kg',
    type: 'Pork Hind Shank, Local',
  },
  {
    id: 'pork-meat-products-pork-loin-imported',
    name: 'Pork Loin, Imported',
    category: COMMODITY_CATEGORIES.PORK_MEAT_PRODUCTS,
    unit: 'kg',
    type: 'Pork Loin, Imported',
  },
  {
    id: 'pork-meat-products-pork-loin-local',
    name: 'Pork Loin, Local',
    category: COMMODITY_CATEGORIES.PORK_MEAT_PRODUCTS,
    unit: 'kg',
    type: 'Pork Loin, Local',
  },
  {
    id: 'pork-meat-products-pork-offals-imported',
    name: 'Pork Offals, Imported',
    category: COMMODITY_CATEGORIES.PORK_MEAT_PRODUCTS,
    unit: 'kg',
    type: 'Pork Offals, Imported',
  },
  {
    id: 'pork-meat-products-pork-offals-local',
    name: 'Pork Offals, Local',
    category: COMMODITY_CATEGORIES.PORK_MEAT_PRODUCTS,
    unit: 'kg',
    type: 'Pork Offals, Local',
  },
  {
    id: 'pork-meat-products-pork-picnic-shoulder-kasim-imported',
    name: 'Pork Picnic Shoulder (Kasim), Imported',
    category: COMMODITY_CATEGORIES.PORK_MEAT_PRODUCTS,
    unit: 'kg',
    type: 'Pork Picnic Shoulder (Kasim), Imported',
  },
  {
    id: 'pork-meat-products-pork-picnic-shoulder-kasim-local',
    name: 'Pork Picnic Shoulder (Kasim), Local',
    category: COMMODITY_CATEGORIES.PORK_MEAT_PRODUCTS,
    unit: 'kg',
    type: 'Pork Picnic Shoulder (Kasim), Local',
  },
  {
    id: 'pork-meat-products-pork-rindskin-imported',
    name: 'Pork Rind/Skin, Imported',
    category: COMMODITY_CATEGORIES.PORK_MEAT_PRODUCTS,
    unit: 'kg',
    type: 'Pork Rind/Skin, Imported',
  },
  {
    id: 'pork-meat-products-pork-rindskin-local',
    name: 'Pork Rind/Skin, Local',
    category: COMMODITY_CATEGORIES.PORK_MEAT_PRODUCTS,
    unit: 'kg',
    type: 'Pork Rind/Skin, Local',
  },
  {
    id: 'pork-meat-products-pork-spare-ribs-imported',
    name: 'Pork Spare Ribs, Imported',
    category: COMMODITY_CATEGORIES.PORK_MEAT_PRODUCTS,
    unit: 'kg',
    type: 'Pork Spare Ribs, Imported',
  },
  {
    id: 'pork-meat-products-pork-spare-ribs-local',
    name: 'Pork Spare Ribs, Local',
    category: COMMODITY_CATEGORIES.PORK_MEAT_PRODUCTS,
    unit: 'kg',
    type: 'Pork Spare Ribs, Local',
  },
  {
    id: 'poultry-products-chicken-breast-imported',
    name: 'Chicken Breast, Imported',
    category: COMMODITY_CATEGORIES.POULTRY_PRODUCTS,
    unit: 'kg',
    type: 'Chicken Breast, Imported',
  },
  {
    id: 'poultry-products-chicken-breast-local-bounty-fresh',
    name: 'Chicken Breast, Local',
    category: COMMODITY_CATEGORIES.POULTRY_PRODUCTS,
    unit: 'kg',
    type: 'Chicken Breast, Local',
    specification: 'Bounty Fresh',
  },
  {
    id: 'poultry-products-chicken-breast-local-magnolia',
    name: 'Chicken Breast, Local',
    category: COMMODITY_CATEGORIES.POULTRY_PRODUCTS,
    unit: 'kg',
    type: 'Chicken Breast, Local',
    specification: 'Magnolia',
  },
  {
    id: 'poultry-products-chicken-breast-local-unbranded-fresh',
    name: 'Chicken Breast, Local',
    category: COMMODITY_CATEGORIES.POULTRY_PRODUCTS,
    unit: 'kg',
    type: 'Chicken Breast, Local',
    specification: 'Unbranded, Fresh',
  },
  {
    id: 'poultry-products-chicken-drumstick-imported',
    name: 'Chicken Drumstick, Imported',
    category: COMMODITY_CATEGORIES.POULTRY_PRODUCTS,
    unit: 'kg',
    type: 'Chicken Drumstick, Imported',
  },
  {
    id: 'poultry-products-chicken-drumstick-local-bounty-fresh',
    name: 'Chicken Drumstick, Local',
    category: COMMODITY_CATEGORIES.POULTRY_PRODUCTS,
    unit: 'kg',
    type: 'Chicken Drumstick, Local',
    specification: 'Bounty Fresh',
  },
  {
    id: 'poultry-products-chicken-drumstick-local-magnolia',
    name: 'Chicken Drumstick, Local',
    category: COMMODITY_CATEGORIES.POULTRY_PRODUCTS,
    unit: 'kg',
    type: 'Chicken Drumstick, Local',
    specification: 'Magnolia',
  },
  {
    id: 'poultry-products-chicken-drumstick-local-unbranded-fresh',
    name: 'Chicken Drumstick, Local',
    category: COMMODITY_CATEGORIES.POULTRY_PRODUCTS,
    unit: 'kg',
    type: 'Chicken Drumstick, Local',
    specification: 'Unbranded, Fresh',
  },
  {
    id: 'poultry-products-chicken-egg-brown-extra-large-per-piece',
    name: 'Chicken Egg (Brown, Extra Large)',
    category: COMMODITY_CATEGORIES.POULTRY_PRODUCTS,
    unit: 'piece',
    type: 'Chicken Egg (Brown, Extra Large)',
    specification: 'per piece',
  },
  {
    id: 'poultry-products-chicken-egg-brown-large-per-piece',
    name: 'Chicken Egg (Brown, Large)',
    category: COMMODITY_CATEGORIES.POULTRY_PRODUCTS,
    unit: 'piece',
    type: 'Chicken Egg (Brown, Large)',
    specification: 'per piece',
  },
  {
    id: 'poultry-products-chicken-egg-brown-medium-per-piece',
    name: 'Chicken Egg (Brown, Medium)',
    category: COMMODITY_CATEGORIES.POULTRY_PRODUCTS,
    unit: 'piece',
    type: 'Chicken Egg (Brown, Medium)',
    specification: 'per piece',
  },
  {
    id: 'poultry-products-chicken-egg-white-extra-large-per-piece',
    name: 'Chicken Egg (White, Extra Large)',
    category: COMMODITY_CATEGORIES.POULTRY_PRODUCTS,
    unit: 'piece',
    type: 'Chicken Egg (White, Extra Large)',
    specification: 'per piece',
  },
  {
    id: 'poultry-products-chicken-egg-white-extra-small-per-piece',
    name: 'Chicken Egg (White, Extra Small)',
    category: COMMODITY_CATEGORIES.POULTRY_PRODUCTS,
    unit: 'piece',
    type: 'Chicken Egg (White, Extra Small)',
    specification: 'per piece',
  },
  {
    id: 'poultry-products-chicken-egg-white-jumbo-per-piece',
    name: 'Chicken Egg (White, Jumbo)',
    category: COMMODITY_CATEGORIES.POULTRY_PRODUCTS,
    unit: 'piece',
    type: 'Chicken Egg (White, Jumbo)',
    specification: 'per piece',
  },
  {
    id: 'poultry-products-chicken-egg-white-large-per-piece',
    name: 'Chicken Egg (White, Large)',
    category: COMMODITY_CATEGORIES.POULTRY_PRODUCTS,
    unit: 'piece',
    type: 'Chicken Egg (White, Large)',
    specification: 'per piece',
  },
  {
    id: 'poultry-products-chicken-egg-white-medium-56-60-gramspc',
    name: 'Chicken Egg (White, Medium)',
    category: COMMODITY_CATEGORIES.POULTRY_PRODUCTS,
    unit: 'piece',
    type: 'Chicken Egg (White, Medium)',
    specification: '56-60 grams/pc',
  },
  {
    id: 'poultry-products-chicken-egg-white-pewee-per-piece',
    name: 'Chicken Egg (White, Pewee)',
    category: COMMODITY_CATEGORIES.POULTRY_PRODUCTS,
    unit: 'piece',
    type: 'Chicken Egg (White, Pewee)',
    specification: 'per piece',
  },
  {
    id: 'poultry-products-chicken-egg-white-small-per-piece',
    name: 'Chicken Egg (White, Small)',
    category: COMMODITY_CATEGORIES.POULTRY_PRODUCTS,
    unit: 'piece',
    type: 'Chicken Egg (White, Small)',
    specification: 'per piece',
  },
  {
    id: 'poultry-products-chicken-feet-imported',
    name: 'Chicken Feet, Imported',
    category: COMMODITY_CATEGORIES.POULTRY_PRODUCTS,
    unit: 'kg',
    type: 'Chicken Feet, Imported',
  },
  {
    id: 'poultry-products-chicken-feet-local',
    name: 'Chicken Feet, Local',
    category: COMMODITY_CATEGORIES.POULTRY_PRODUCTS,
    unit: 'kg',
    type: 'Chicken Feet, Local',
  },
  {
    id: 'poultry-products-chicken-leg-quarter-bounty-fresh',
    name: 'Chicken Leg Quarter',
    category: COMMODITY_CATEGORIES.POULTRY_PRODUCTS,
    unit: 'kg',
    type: 'Chicken Leg Quarter',
    specification: 'Bounty Fresh',
  },
  {
    id: 'poultry-products-chicken-leg-quarter-magnolia',
    name: 'Chicken Leg Quarter',
    category: COMMODITY_CATEGORIES.POULTRY_PRODUCTS,
    unit: 'kg',
    type: 'Chicken Leg Quarter',
    specification: 'Magnolia',
  },
  {
    id: 'poultry-products-chicken-leg-quarter-unbranded-fresh',
    name: 'Chicken Leg Quarter',
    category: COMMODITY_CATEGORIES.POULTRY_PRODUCTS,
    unit: 'kg',
    type: 'Chicken Leg Quarter',
    specification: 'Unbranded, Fresh',
  },
  {
    id: 'poultry-products-chicken-leg-quarter-imported',
    name: 'Chicken Leg Quarter, Imported',
    category: COMMODITY_CATEGORIES.POULTRY_PRODUCTS,
    unit: 'kg',
    type: 'Chicken Leg Quarter, Imported',
  },
  {
    id: 'poultry-products-chicken-liver-imported',
    name: 'Chicken Liver, Imported',
    category: COMMODITY_CATEGORIES.POULTRY_PRODUCTS,
    unit: 'kg',
    type: 'Chicken Liver, Imported',
  },
  {
    id: 'poultry-products-chicken-liver-local',
    name: 'Chicken Liver, Local',
    category: COMMODITY_CATEGORIES.POULTRY_PRODUCTS,
    unit: 'kg',
    type: 'Chicken Liver, Local',
  },
  {
    id: 'poultry-products-chicken-neck-imported',
    name: 'Chicken Neck, Imported',
    category: COMMODITY_CATEGORIES.POULTRY_PRODUCTS,
    unit: 'kg',
    type: 'Chicken Neck, Imported',
  },
  {
    id: 'poultry-products-chicken-neck-local',
    name: 'Chicken Neck, Local',
    category: COMMODITY_CATEGORIES.POULTRY_PRODUCTS,
    unit: 'kg',
    type: 'Chicken Neck, Local',
  },
  {
    id: 'poultry-products-chicken-rindskin-imported',
    name: 'Chicken Rind/Skin, Imported',
    category: COMMODITY_CATEGORIES.POULTRY_PRODUCTS,
    unit: 'kg',
    type: 'Chicken Rind/Skin, Imported',
  },
  {
    id: 'poultry-products-chicken-rindskin-local',
    name: 'Chicken Rind/Skin, Local',
    category: COMMODITY_CATEGORIES.POULTRY_PRODUCTS,
    unit: 'kg',
    type: 'Chicken Rind/Skin, Local',
  },
  {
    id: 'poultry-products-chicken-thigh-imported',
    name: 'Chicken Thigh, Imported',
    category: COMMODITY_CATEGORIES.POULTRY_PRODUCTS,
    unit: 'kg',
    type: 'Chicken Thigh, Imported',
  },
  {
    id: 'poultry-products-chicken-thigh-local',
    name: 'Chicken Thigh, Local',
    category: COMMODITY_CATEGORIES.POULTRY_PRODUCTS,
    unit: 'kg',
    type: 'Chicken Thigh, Local',
  },
  {
    id: 'poultry-products-chicken-wing-imported',
    name: 'Chicken Wing, Imported',
    category: COMMODITY_CATEGORIES.POULTRY_PRODUCTS,
    unit: 'kg',
    type: 'Chicken Wing, Imported',
  },
  {
    id: 'poultry-products-chicken-wing-local-bounty-fresh',
    name: 'Chicken Wing, Local',
    category: COMMODITY_CATEGORIES.POULTRY_PRODUCTS,
    unit: 'kg',
    type: 'Chicken Wing, Local',
    specification: 'Bounty Fresh',
  },
  {
    id: 'poultry-products-chicken-wing-local-magnolia',
    name: 'Chicken Wing, Local',
    category: COMMODITY_CATEGORIES.POULTRY_PRODUCTS,
    unit: 'kg',
    type: 'Chicken Wing, Local',
    specification: 'Magnolia',
  },
  {
    id: 'poultry-products-chicken-wing-local-unbranded-fresh',
    name: 'Chicken Wing, Local',
    category: COMMODITY_CATEGORIES.POULTRY_PRODUCTS,
    unit: 'kg',
    type: 'Chicken Wing, Local',
    specification: 'Unbranded, Fresh',
  },
  {
    id: 'poultry-products-duck-meat-imported',
    name: 'Duck Meat, Imported',
    category: COMMODITY_CATEGORIES.POULTRY_PRODUCTS,
    unit: 'kg',
    type: 'Duck Meat, Imported',
  },
  {
    id: 'poultry-products-duck-meat-local',
    name: 'Duck Meat, Local',
    category: COMMODITY_CATEGORIES.POULTRY_PRODUCTS,
    unit: 'kg',
    type: 'Duck Meat, Local',
  },
  {
    id: 'poultry-products-peckin-duck-imported',
    name: 'Peckin Duck, Imported',
    category: COMMODITY_CATEGORIES.POULTRY_PRODUCTS,
    unit: 'kg',
    type: 'Peckin Duck, Imported',
  },
  {
    id: 'poultry-products-peckin-duck-local',
    name: 'Peckin Duck, Local',
    category: COMMODITY_CATEGORIES.POULTRY_PRODUCTS,
    unit: 'kg',
    type: 'Peckin Duck, Local',
  },
  {
    id: 'poultry-products-whole-chicken-imported',
    name: 'Whole Chicken, Imported',
    category: COMMODITY_CATEGORIES.POULTRY_PRODUCTS,
    unit: 'kg',
    type: 'Whole Chicken, Imported',
  },
  {
    id: 'poultry-products-whole-chicken-local-bounty-fresh',
    name: 'Whole Chicken, Local',
    category: COMMODITY_CATEGORIES.POULTRY_PRODUCTS,
    unit: 'kg',
    type: 'Whole Chicken, Local',
    specification: 'Bounty Fresh',
  },
  {
    id: 'poultry-products-whole-chicken-local-fully-dressed',
    name: 'Whole Chicken, Local',
    category: COMMODITY_CATEGORIES.POULTRY_PRODUCTS,
    unit: 'kg',
    type: 'Whole Chicken, Local',
    specification: 'Fully Dressed',
  },
  {
    id: 'poultry-products-whole-chicken-local-magnolia',
    name: 'Whole Chicken, Local',
    category: COMMODITY_CATEGORIES.POULTRY_PRODUCTS,
    unit: 'kg',
    type: 'Whole Chicken, Local',
    specification: 'Magnolia',
  },
  {
    id: 'spices-chili-siling-labuyo',
    name: 'Chili (Siling Labuyo)',
    category: COMMODITY_CATEGORIES.SPICES,
    unit: 'kg',
    type: 'Chili (Siling Labuyo)',
  },
  {
    id: 'spices-chilli-red-local-tingala',
    name: 'Chilli (Red), Local',
    category: COMMODITY_CATEGORIES.SPICES,
    unit: 'kg',
    type: 'Chilli (Red), Local',
    specification: 'Tingala',
  },
  {
    id: 'spices-garlic-imported',
    name: 'Garlic, Imported',
    category: COMMODITY_CATEGORIES.SPICES,
    unit: 'kg',
    type: 'Garlic, Imported',
  },
  {
    id: 'spices-garlic-nativelocal',
    name: 'Garlic, Native/Local',
    category: COMMODITY_CATEGORIES.SPICES,
    unit: 'kg',
    type: 'Garlic, Native/Local',
  },
  {
    id: 'spices-ginger-luya',
    name: 'Ginger (Luya)',
    category: COMMODITY_CATEGORIES.SPICES,
    unit: 'kg',
    type: 'Ginger (Luya)',
  },
  {
    id: 'spices-ginger-imported-fairly-well-matured-medium-150-300-gm',
    name: 'Ginger, Imported',
    category: COMMODITY_CATEGORIES.SPICES,
    unit: 'kg',
    type: 'Ginger, Imported',
    specification: 'Fairly well-matured, Medium (150-300 gm)',
  },
  {
    id: 'spices-ginger-local-fairly-well-matured-medium-150-300-gm',
    name: 'Ginger, Local',
    category: COMMODITY_CATEGORIES.SPICES,
    unit: 'kg',
    type: 'Ginger, Local',
    specification: 'Fairly well-matured, Medium (150-300 gm)',
  },
  {
    id: 'spices-red-onion-imported',
    name: 'Red Onion, Imported',
    category: COMMODITY_CATEGORIES.SPICES,
    unit: 'kg',
    type: 'Red Onion, Imported',
  },
  {
    id: 'spices-red-onion-local-13-15-pcskg',
    name: 'Red Onion, Local',
    category: COMMODITY_CATEGORIES.SPICES,
    unit: 'kg',
    type: 'Red Onion, Local',
    specification: '13-15 pcs/kg',
  },
  {
    id: 'spices-tiger-chillies-imported-tiger-chillies-imported',
    name: 'Tiger Chillies, Imported',
    category: COMMODITY_CATEGORIES.SPICES,
    unit: 'kg',
    type: 'Tiger Chillies, Imported',
    specification: 'Tiger Chillies, Imported',
  },
  {
    id: 'spices-white-onion-imported-large',
    name: 'White Onion, Imported',
    category: COMMODITY_CATEGORIES.SPICES,
    unit: 'kg',
    type: 'White Onion, Imported',
    specification: 'Large',
  },
  {
    id: 'spices-white-onion-imported-medium',
    name: 'White Onion, Imported',
    category: COMMODITY_CATEGORIES.SPICES,
    unit: 'kg',
    type: 'White Onion, Imported',
    specification: 'Medium',
  },
  {
    id: 'spices-white-onion-local',
    name: 'White Onion, Local',
    category: COMMODITY_CATEGORIES.SPICES,
    unit: 'kg',
    type: 'White Onion, Local',
  }
];